# Generated by Django 4.2.4 on 2023-11-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
