# Generated by Django 4.2.4 on 2023-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usuario_date_joined_alter_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
