# Generated by Django 4.2.4 on 2023-09-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usuario_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to=''),
        ),
    ]
