# Generated by Django 4.2.4 on 2023-11-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
