# Generated by Django 4.2.4 on 2023-11-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='es_destacada',
            field=models.BooleanField(default=False),
        ),
    ]
