# Generated by Django 4.2.4 on 2023-11-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_respuesta_es_destacada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='es_destacada',
            new_name='destacada',
        ),
    ]
