# Generated by Django 4.2.4 on 2023-10-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
